In [7]:
import numpy as np 
import matplotlib.pyplot as plt


b = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

B = np.array(b)
B
B.ndim


9

In [8]:
B.shape

(3, 3)

In [9]:
B.size

9

In [10]:
b


[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [11]:
B

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [13]:
B[1, 2]

23

In [14]:
B[1][2]

23

In [16]:
B[0][0:3]

array([11, 12, 13])

In [17]:
B[0:2, 2]

array([13, 23])

In [19]:
X = np.array([[98, 45], [62, 94]])
X

array([[98, 45],
       [62, 94]])

In [20]:
Y = np.array([[53, 29], [76, 47]])
Y

array([[53, 29],
       [76, 47]])

In [24]:
R = 2*Y
R

array([[106,  58],
       [152,  94]])

In [22]:
Z = X + Y
Z

array([[151,  74],
       [138, 141]])

In [26]:
J = X*Y
J

array([[5194, 1305],
       [4712, 4418]])

In [27]:
Q = np.dot(X,Y)
Q

array([[ 8614,  4957],
       [10430,  6216]])

In [28]:
S = np.sin(Q)
S

array([[-0.24455055, -0.41978404],
       [-0.08749789,  0.93627151]])

In [29]:
 U = S.T
U

array([[-0.24455055, -0.08749789],
       [-0.41978404,  0.93627151]])