In [34]:

import numpy as np #importing numpy 
distance = [10,20,30,40]
time = [2,4,2,2]

np.version.version
np_dist = np.array(distance)
np_time = np.array(time)
np_dist/np_time
np_dist//np_time
print(np_dist//np_time)
A = [1,2,3,4,5]
one_darray = np.array(A) #syntax to create one dimensional array
one_darray
print(one_darray)
two_darray = np.array([[1,2,3],[4,5,6]]) #syntax to create two dimensional array
print(two_darray)
three_darray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[6,8,3],[8,6,7]]]) #syntax to create three dimensional array
print(three_darray)
three_darray.ndim
three_darray.dtype
three_darray.shape
three_darray.size
one_darray1 = np.array(['India','USA','China','eNGLAND'])
one_darray1.ndim
one_darray1.shape
one_darray1.size
one_darray1.dtype
score = np.array([80,90,40,30,20,40,50])


cities_array = np.array([['India','Delhi'],['England','london']])

cities_array

one_darray

one_darray1

a = np.array([1,2,3,4,5])
b = np.array([5,3,6,3,7])

a+b

a-b

a/b

b/a

a*b

b*a

a**b


b**a

b//a

3 & 3 # bitwise operator

2&3

2|3

score = np.array([80,90,40,30,20,40,50])

(score > 40) & (score<90)

score[(score > 40) & (score < 90)]

score[(score >= 40) & (score <=90)]

passed_score = score[(score >=40) & (score <=90)]

passed_score

two_darray[0]

two_darray[1]

two_darray[0][0]

two_darray[0][1]

two_darray[0][2]

two_darray[1][0]

two_darray[1][2]

two_darray[1][2]



[ 5  5 15 20]
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 6  8  3]
  [ 8  6  7]]]


6